{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.opal",
    "module": "opal-push-fcm",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-push-fcm-4.0.0.aar",
          "url": "opal-push-fcm-4.0.0.aar",
          "size": 159751,
          "sha512": "879cd753bf36bd525345d48b02e730641e4e869d930006eca16ded8b0fc9ab80f1fb6392a2525573741d217921f3d8c0e15f6b474511b1bfe876ec8122c8844a",
          "sha256": "69851eee8f61d03ef1a9dd00b87319b33cf19b2e3cc838af15fae2003ddd1238",
          "sha1": "28fe3540e144938c5d247b10d098c77dba645409",
          "md5": "95094dae9aa16b68e72ab24578a6c349"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-push-fcm-4.0.0.aar",
          "url": "opal-push-fcm-4.0.0.aar",
          "size": 159751,
          "sha512": "879cd753bf36bd525345d48b02e730641e4e869d930006eca16ded8b0fc9ab80f1fb6392a2525573741d217921f3d8c0e15f6b474511b1bfe876ec8122c8844a",
          "sha256": "69851eee8f61d03ef1a9dd00b87319b33cf19b2e3cc838af15fae2003ddd1238",
          "sha1": "28fe3540e144938c5d247b10d098c77dba645409",
          "md5": "95094dae9aa16b68e72ab24578a6c349"
        }
      ]
    }
  ]
}
