{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.opal",
    "module": "opal-core",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-android"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "25.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-core-4.0.0.aar",
          "url": "opal-core-4.0.0.aar",
          "size": 266740,
          "sha512": "fe5ed924c463a46cb5b74be286e00a9927c08f51c9578b9ffd7609ddb2a6c3ae1e55d4d50b7522177be9d7b5c75b780b74b907c50a18c947ee1abc039df5f48a",
          "sha256": "f68e2c34b129f8ff901cdb8b72a6344133aab1da134caeaf2857ca2d082a1109",
          "sha1": "c0ef0c9fc8c03a7988e98500f9e34dc18d9b9415",
          "md5": "ffac7dd8a393df29c3a4bb453eb7323d"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-android"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "25.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-core-4.0.0.aar",
          "url": "opal-core-4.0.0.aar",
          "size": 266740,
          "sha512": "fe5ed924c463a46cb5b74be286e00a9927c08f51c9578b9ffd7609ddb2a6c3ae1e55d4d50b7522177be9d7b5c75b780b74b907c50a18c947ee1abc039df5f48a",
          "sha256": "f68e2c34b129f8ff901cdb8b72a6344133aab1da134caeaf2857ca2d082a1109",
          "sha1": "c0ef0c9fc8c03a7988e98500f9e34dc18d9b9415",
          "md5": "ffac7dd8a393df29c3a4bb453eb7323d"
        }
      ]
    }
  ]
}
