{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.opal",
    "module": "opal-analytics",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-analytics-4.0.1.aar",
          "url": "opal-analytics-4.0.1.aar",
          "size": 33528,
          "sha512": "dc79af4e913269abcc2cf1894517a4218e15133e30874b0ff9e30f1816694c2fb70e6336b2df3db01da3ba65abb6ed0cf11086a9620b4bc48bb5a818b44bbab5",
          "sha256": "e6a50df278855989b9cb05f343ec070ff13e3fc7fc1c351ea3cbd84ed200bd74",
          "sha1": "79224080a755c7659bb2d6eee3847729f7f91469",
          "md5": "19696a204cb1d13c04c17618066f42e6"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-analytics-4.0.1.aar",
          "url": "opal-analytics-4.0.1.aar",
          "size": 33528,
          "sha512": "dc79af4e913269abcc2cf1894517a4218e15133e30874b0ff9e30f1816694c2fb70e6336b2df3db01da3ba65abb6ed0cf11086a9620b4bc48bb5a818b44bbab5",
          "sha256": "e6a50df278855989b9cb05f343ec070ff13e3fc7fc1c351ea3cbd84ed200bd74",
          "sha1": "79224080a755c7659bb2d6eee3847729f7f91469",
          "md5": "19696a204cb1d13c04c17618066f42e6"
        }
      ]
    }
  ]
}
