{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.opal",
    "module": "opal-analytics",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-analytics-4.0.0.aar",
          "url": "opal-analytics-4.0.0.aar",
          "size": 33333,
          "sha512": "182997152fed8cf4e6c4540bfb845da755c0aa3ddcd29249aacbe37abfd862c18eb8f2d4345bb1f13b417a4ce33a128000006a2e164ab8cba0960f8a3d8134ca",
          "sha256": "ed944ecb3b50f99245d1daa5d59efb30395d5ee07c0095de276f940871726060",
          "sha1": "c044a18e30cc2eb989bda69321bcb3a5d9630564",
          "md5": "3ef3d29a236c734071d4ef3d9c2705f9"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-analytics-4.0.0.aar",
          "url": "opal-analytics-4.0.0.aar",
          "size": 33333,
          "sha512": "182997152fed8cf4e6c4540bfb845da755c0aa3ddcd29249aacbe37abfd862c18eb8f2d4345bb1f13b417a4ce33a128000006a2e164ab8cba0960f8a3d8134ca",
          "sha256": "ed944ecb3b50f99245d1daa5d59efb30395d5ee07c0095de276f940871726060",
          "sha1": "c044a18e30cc2eb989bda69321bcb3a5d9630564",
          "md5": "3ef3d29a236c734071d4ef3d9c2705f9"
        }
      ]
    }
  ]
}
