{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.opal",
    "module": "opal-inapp",
    "version": "4.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-inapp-4.0.2.aar",
          "url": "opal-inapp-4.0.2.aar",
          "size": 319865,
          "sha512": "83a9b6509b825f5e86bc86e9118181ea8cd855298e553c7e9e495d992304ef18e44e36417bc84c9c199327c49d3eed9c4630f71169683795daa0786e8dd6d46e",
          "sha256": "a9e4f1fa525a28c51c8e705773b13cdafe7e3e1405288f0b937234b2be679509",
          "sha1": "70f7cbb60886937678122fbf7114af1f26fa6452",
          "md5": "7fb59bce2dbeb0546a27f3a9f1b6335c"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.play",
          "module": "review",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-inapp-4.0.2.aar",
          "url": "opal-inapp-4.0.2.aar",
          "size": 319865,
          "sha512": "83a9b6509b825f5e86bc86e9118181ea8cd855298e553c7e9e495d992304ef18e44e36417bc84c9c199327c49d3eed9c4630f71169683795daa0786e8dd6d46e",
          "sha256": "a9e4f1fa525a28c51c8e705773b13cdafe7e3e1405288f0b937234b2be679509",
          "sha1": "70f7cbb60886937678122fbf7114af1f26fa6452",
          "md5": "7fb59bce2dbeb0546a27f3a9f1b6335c"
        }
      ]
    }
  ]
}
