{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.opal",
    "module": "opal-inapp",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-inapp-4.0.1.aar",
          "url": "opal-inapp-4.0.1.aar",
          "size": 319865,
          "sha512": "24687e4be2f15809da76e64b4a8adff564ce2d3805ecff4dc57e733a767273fb14d42091e448f1fe8790bfe938c6c0e6aef0f7fc5362cc04fbbcf8c89f977111",
          "sha256": "0632955b9a81d6c11ba32ad24565d0a932e3d0f5d3d6c505d29f865f925fef3c",
          "sha1": "be5ab29f565ac50c29693c2172b9c8d801056917",
          "md5": "adf6f43e3a06d0d79cc38f366bcdf0f5"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.play",
          "module": "review",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-inapp-4.0.1.aar",
          "url": "opal-inapp-4.0.1.aar",
          "size": 319865,
          "sha512": "24687e4be2f15809da76e64b4a8adff564ce2d3805ecff4dc57e733a767273fb14d42091e448f1fe8790bfe938c6c0e6aef0f7fc5362cc04fbbcf8c89f977111",
          "sha256": "0632955b9a81d6c11ba32ad24565d0a932e3d0f5d3d6c505d29f865f925fef3c",
          "sha1": "be5ab29f565ac50c29693c2172b9c8d801056917",
          "md5": "adf6f43e3a06d0d79cc38f366bcdf0f5"
        }
      ]
    }
  ]
}
