{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.opal",
    "module": "opal-inapp",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-inapp-4.0.0.aar",
          "url": "opal-inapp-4.0.0.aar",
          "size": 318868,
          "sha512": "73b4eae18a8b9f4b459243246b8fdfee112e3be442077740c7811fce949109382dc2db9fd16921317b9b03fbed462567b738a839dd67349aeddcdd4bbb6950a8",
          "sha256": "04bcb133562eb82c611661c7bddcfd5fd6517a385dc3b902d9d195e1feb5c536",
          "sha1": "f4737dc1e12baf56d0c25c4c4074b33d1a5b93ef",
          "md5": "ec65e79941e5ce5ff921a2eb40e80135"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.play",
          "module": "review",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-inapp-4.0.0.aar",
          "url": "opal-inapp-4.0.0.aar",
          "size": 318868,
          "sha512": "73b4eae18a8b9f4b459243246b8fdfee112e3be442077740c7811fce949109382dc2db9fd16921317b9b03fbed462567b738a839dd67349aeddcdd4bbb6950a8",
          "sha256": "04bcb133562eb82c611661c7bddcfd5fd6517a385dc3b902d9d195e1feb5c536",
          "sha1": "f4737dc1e12baf56d0c25c4c4074b33d1a5b93ef",
          "md5": "ec65e79941e5ce5ff921a2eb40e80135"
        }
      ]
    }
  ]
}
