{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.opal",
    "module": "opal-analytics-compose",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ai.opal",
          "module": "opal-analytics",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-analytics-compose-4.0.0.aar",
          "url": "opal-analytics-compose-4.0.0.aar",
          "size": 4475,
          "sha512": "d0f29560519d8e5949b8c6de15f127e5e5f15402d20ccef562ca02aeec600fc8dc5e6aa2dfd5be69f3afad7ba1ab56200503da5f7d8472bc376ec3a39efe4b05",
          "sha256": "f70672de52fa565543600472ef51a7203a79e489417acc907710aa1b7878b178",
          "sha1": "67d17fa274e57e2299cee2ec7c71f578e81fce17",
          "md5": "2c0c2c426e09dda65c664831c9e4a25c"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ai.opal",
          "module": "opal-analytics",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-android",
          "version": {
            "requires": "1.9.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-analytics-compose-4.0.0.aar",
          "url": "opal-analytics-compose-4.0.0.aar",
          "size": 4475,
          "sha512": "d0f29560519d8e5949b8c6de15f127e5e5f15402d20ccef562ca02aeec600fc8dc5e6aa2dfd5be69f3afad7ba1ab56200503da5f7d8472bc376ec3a39efe4b05",
          "sha256": "f70672de52fa565543600472ef51a7203a79e489417acc907710aa1b7878b178",
          "sha1": "67d17fa274e57e2299cee2ec7c71f578e81fce17",
          "md5": "2c0c2c426e09dda65c664831c9e4a25c"
        }
      ]
    }
  ]
}
