{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.opal",
    "module": "opal-core",
    "version": "4.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-android"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "25.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-core-4.0.2.aar",
          "url": "opal-core-4.0.2.aar",
          "size": 267113,
          "sha512": "7f4f3f8829b681617ed5ba979e75b8170e5a80747319068ce61f7470e004806e26ca73d10fc85b1149fe19526073c1389e0a98694a2293a74402b1f6bb24f9de",
          "sha256": "e4a90751ba521a99875da19200d8f11ec2d2efee9ab5f68bf1c7803e9127279c",
          "sha1": "8ab65f869fcd7aa370538ae17ee4ca8dcf06dfe3",
          "md5": "994190bcd3701a2d591b980b5da07e5b"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-android"
          }
        },
        {
          "group": "com.android.volley",
          "module": "volley",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "version": {
            "requires": "25.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "opal-core-4.0.2.aar",
          "url": "opal-core-4.0.2.aar",
          "size": 267113,
          "sha512": "7f4f3f8829b681617ed5ba979e75b8170e5a80747319068ce61f7470e004806e26ca73d10fc85b1149fe19526073c1389e0a98694a2293a74402b1f6bb24f9de",
          "sha256": "e4a90751ba521a99875da19200d8f11ec2d2efee9ab5f68bf1c7803e9127279c",
          "sha1": "8ab65f869fcd7aa370538ae17ee4ca8dcf06dfe3",
          "md5": "994190bcd3701a2d591b980b5da07e5b"
        }
      ]
    }
  ]
}
